#pragma once

#include <stdint.h>

/**
 * @file audio_samples.h
 *
 * Pre-recorded Chinese voice responses stored as 16-bit PCM mono at 16kHz.
 *
 * In production, these arrays are generated by tools/encode_audio.py
 * from real .wav recordings. The current content is placeholder beeps.
 */

/* ── audio clip descriptor ────────────────────────── */
typedef struct {
    const int16_t *data;
    uint32_t        len;    /* sample count */
} clip_desc_t;

void audio_samples_load(clip_desc_t *clips);
