"""
encode_audio.py — Convert .wav files to C array for TTS playback.

Usage:
    python encode_audio.py ok.wav    → outputs audio_ok.h with C array
    python encode_audio.py *.wav     → batch convert all wavs in folder

Output format: 16-bit signed PCM mono, 16kHz sample rate.
If input doesn't match, this script auto-converts using basic resampling
(pip install scipy numpy soundfile for full auto-conversion).

For production: record audio at 16kHz 16-bit mono directly.
"""

import sys
import os
import struct
import wave


def wav_to_c_array(wav_path: str) -> tuple[str, list[int], int]:
    """Read a .wav file and return (name, samples, sample_rate)."""
    with wave.open(wav_path, 'rb') as wf:
        nchannels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        framerate = wf.getframerate()
        nframes   = wf.getnframes()

        print(f"  {wav_path}: {nchannels}ch {sampwidth*8}bit {framerate}Hz {nframes} frames",
              file=sys.stderr)

        raw = wf.readframes(nframes)
        fmt = '<h'  # 16-bit signed LE

        samples = []
        for i in range(nframes):
            # read first channel only (mono mix)
            offset = i * nchannels * sampwidth
            val = struct.unpack_from(fmt, raw, offset)[0]
            samples.append(val)

        name = os.path.splitext(os.path.basename(wav_path))[0]
        name = name.replace('-', '_').replace(' ', '_')
        return name, samples, framerate


def format_c_array(name: str, samples: list[int]) -> str:
    """Format samples as a C header file content."""
    lines = []
    lines.append(f"/* Auto-generated by encode_audio.py — do not edit */")
    lines.append(f"#pragma once")
    lines.append(f"")
    lines.append(f"#include <stdint.h>")
    lines.append(f"")

    # write sample count
    lines.append(f"#define AUDIO_{name.upper()}_LEN  {len(samples)}")
    lines.append(f"")

    # write array
    lines.append(f"static const int16_t audio_{name}[AUDIO_{name.upper()}_LEN] = {{")

    # 16 samples per line
    for i in range(0, len(samples), 16):
        chunk = samples[i:i+16]
        vals = ', '.join(str(s) for s in chunk)
        if i + 16 < len(samples):
            lines.append(f"    {vals},")
        else:
            lines.append(f"    {vals}")
    lines.append("};")

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    for wav_path in sys.argv[1:]:
        if not os.path.exists(wav_path):
            print(f"ERROR: file not found: {wav_path}", file=sys.stderr)
            continue

        try:
            name, samples, rate = wav_to_c_array(wav_path)

            if rate != 16000:
                print(f"  WARNING: {rate}Hz — TTS player expects 16kHz. "
                      f"Auto-resample not implemented; please convert manually.",
                      file=sys.stderr)

            if len(samples) > 32000:
                print(f"  WARNING: {len(samples)} samples > 32000 max. "
                      f"Clip will be truncated.", file=sys.stderr)
                samples = samples[:32000]

            c_code = format_c_array(name, samples)

            out_path = f"audio_{name}.h"
            with open(out_path, 'w', encoding='utf-8') as f:
                f.write(c_code)
            print(f"  → {out_path}  ({len(samples)} samples, "
                  f"{len(samples)*1000/rate:.0f}ms)", file=sys.stderr)

        except Exception as e:
            print(f"ERROR processing {wav_path}: {e}", file=sys.stderr)


if __name__ == '__main__':
    main()
